version: 2.1
orbs:
  slack: circleci/slack@4.1
commands:
  restore-frontend-cache:
    steps:
      - restore_cache:
          keys: [frontend-build]

  restore-backend-cache:
    steps:
      - restore_cache:
          keys: [backend-build]

  save-frontend-cache:
    steps:
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  save-backend-cache:
    steps:
      - save_cache:
          paths: [backend/node_modules]
          key: frontend-build


jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-frontend-cache
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save-frontend-cache

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-backend-cache
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
      - save-backend-cache
  
  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-frontend-cache
      - run:
          name: Testing the frontend.
          command: |
            cd frontend
            npm install
            npm run test
      
              
  test-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-backend-cache
      - run:
          name: Testing the frontend.
          command: |
            cd backend
            npm install
            npm run test

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-frontend-cache
      - run:
          name: Audit frontend
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack/notify:
          channel: D03PUBCHLAX
          event: fail
          template: basic_fail_1

  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore-backend-cache
      - run:
          name: Audit backend
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - slack/notify:
          channel: D03PUBCHLAX
          event: fail
          template: basic_fail_1

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
          context: slack-secrets
      - scan-backend:
          requires: [build-backend]
          context: slack-secrets